//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Substitution
    {
        public int IngredientID { get; set; }
        public string Ingredient { get; set; }
        public string Substitution1 { get; set; }
        public string Substitution2 { get; set; }
        public string Substitution3 { get; set; }
    }
}
